# Generated by Django 2.1.7 on 2019-03-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word_link',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
