# Generated by Django 2.1.7 on 2019-03-18 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190318_2249'),
    ]

    operations = [
        migrations.DeleteModel(
            name='word_link',
        ),
    ]
