# Generated by Django 2.1.7 on 2019-04-05 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
