# Generated by Django 2.1.7 on 2019-04-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190407_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='time',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
