# Generated by Django 2.1.7 on 2019-04-07 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190407_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
