# Generated by Django 2.1.7 on 2019-03-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='word_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('word_searched', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=100000)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
