# Generated by Django 2.1.7 on 2019-04-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WordLink', '0002_auto_20190407_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word_link',
            name='date_time',
        ),
        migrations.AlterField(
            model_name='word_link',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
