# Generated by Django 2.1.7 on 2019-04-07 09:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WordLink', '0003_auto_20190407_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='word_link',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
